### ISSUE TITLE
Compile bytecode in buildtime to improve performance/reduce snap size

### ISSUE THREAD

**Issue by brlin-tw** [Lin-Buo-Ren/speedtest-cli-snap#4]
Currently, native Python code is packaged instead of compiled bytecode files, pre-compile these files in build time should improve performance, we could probably even strip the origin version out to reduce snap size.

Reference: 

* [Snap performance and troubleshooting issues - snap - snapcraft.io](https://forum.snapcraft.io/t/snap-performance-and-troubleshooting-issues/13324/3)
* [Replace .py with *pyc](https://gist.github.com/orgkd/1d595fab93ef705f05713769a9d5d9cd)

**Comment by brlin-tw** [comment]
The following does not work :(:

```sh
    override-prime: |
      set -u

      snapcraftctl prime

      # Compile all Python code
      "${SNAPCRAFT_STAGE}"/usr/bin/python3 -m compileall \
        -j 0 \
        "${SNAPCRAFT_PRIME}"


      # Drop native code to reduce snap size
      drop_native_py_with_pyc(){
          native_py="${1}"
          native_py_filename="${native_py##*/}"
          native_py_name="${native_py_filename%.*}"
          native_py_dir="${native_py%/*}"

          if test -e "${native_py_dir}/__pycache__/${native_py_name}.cpython-36.pyc"; then
            rm \
              --verbose \
              "${native_py}"
          fi
      }

      for native_py in $(
        find \
          "${SNAPCRAFT_PRIME}" \
          -type f \
          -name '*.py'
      ); do
        drop_native_py_with_pyc \
          "${native_py}"
      done
```

Running the snap fails with: 

```output
snapcraft-speedtest-cli # speedtest-cli 
Traceback (most recent call last):
  File "/snap/speedtest-cli/x10/bin/speedtest-cli", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/speedtest-cli/x10/bin/speedtest-cli", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/speedtest-cli/x10/bin/speedtest-cli", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'speedtest-cli==2.1.3' distribution was not found and is required by the application
```
